/**
 * Database row types — mirror supabase/schema.sql exactly (snake_case).
 *
 * When connecting a real Supabase project, replace with auto-generated output:
 *   npx supabase gen types typescript --project-id <your-id> > types/database.ts
 */

export interface DbService {
  id: string;
  name: string;
  description: string | null;
  duration_minutes: number;
  price_from_eur: number;
  emoji: string | null;
  color_class: string | null;
  border_class: string | null;
  bg_class: string | null;
  active: boolean;
  created_at: string;
}

export interface DbLocation {
  id: string;
  label: string;
  short_label: string;
  emoji: string | null;
  display_range_start: number;
  display_range_end: number;
  operating_weekday_start: number;
  operating_weekday_end: number;
  operating_weekend_start: number;
  operating_weekend_end: number;
}

export interface DbScheduleSlot {
  id: string;
  location_id: string;
  day_of_week: number;   // 1=Mon … 7=Sun
  start_hour: number;
  end_hour: number;
  activity_type: string;
  status: string;
  created_at: string;
}

export interface DbReservation {
  id: string;               // UUID — generated by Postgres (gen_random_uuid())
  service_id: string;
  reservation_date: string; // 'YYYY-MM-DD'
  start_time: string;       // 'HH:MM:SS'
  end_time: string;         // 'HH:MM:SS'
  customer_name: string;
  customer_phone: string;
  note: string;             // NOT NULL, DEFAULT ''
  status: string;
  created_at: string;
}

export interface DbProfile {
  id: string;            // UUID — references auth.users(id)
  email: string;
  full_name: string | null;
  role: string;
  created_at: string;
}
