-- =============================================================================
-- Migration 001 — reservations table (redesign)
-- =============================================================================
-- Replaces the earlier reservations definition in schema.sql with a schema
-- that uses explicit start_time / end_time and normalised customer_* columns.
--
-- Run this in: Supabase Dashboard → SQL Editor
-- Safe to run multiple times (idempotent via IF NOT EXISTS / IF EXISTS guards).
-- =============================================================================

-- Drop old table if it exists from schema.sql initial run
-- (removes dependent policies first)
DROP POLICY IF EXISTS "reservations_anon_insert" ON public.reservations;
DROP POLICY IF EXISTS "reservations_admin_all"   ON public.reservations;
DROP TABLE IF EXISTS public.reservations;

-- ─── reservations ─────────────────────────────────────────────────────────────

CREATE TABLE public.reservations (
  -- Primary key — UUID generated by the database
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Which service is being booked (FK → services)
  service_id        TEXT        NOT NULL REFERENCES public.services(id),

  -- Customer details
  customer_name     TEXT        NOT NULL,
  customer_phone    TEXT        NOT NULL,

  -- When the booking takes place
  reservation_date  DATE        NOT NULL,
  start_time        TIME        NOT NULL,
  end_time          TIME        NOT NULL,

  -- Workflow status
  status            TEXT        NOT NULL DEFAULT 'novo'
                    CHECK (status IN ('novo', 'potvrđeno', 'plaćeno', 'otkazano')),

  -- Optional free-text note from customer or admin
  note              TEXT,

  -- Audit
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Integrity: end must be after start
  CONSTRAINT end_after_start CHECK (end_time > start_time)
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX idx_reservations_date       ON public.reservations (reservation_date);
CREATE INDEX idx_reservations_status     ON public.reservations (status);
CREATE INDEX idx_reservations_service    ON public.reservations (service_id);
CREATE INDEX idx_reservations_created_at ON public.reservations (created_at DESC);

-- Prevent double-booking: no two confirmed/paid reservations for the same
-- service on the same date with overlapping times.
CREATE UNIQUE INDEX idx_reservations_no_overlap
  ON public.reservations (service_id, reservation_date, start_time)
  WHERE status IN ('novo', 'potvrđeno', 'plaćeno');

-- ─── Row Level Security ───────────────────────────────────────────────────────

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Anyone (including unauthenticated visitors) can create a booking
CREATE POLICY "reservations_anon_insert" ON public.reservations
  FOR INSERT WITH CHECK (true);

-- Anyone can read reservations (needed for the public schedule / availability check)
CREATE POLICY "reservations_public_read" ON public.reservations
  FOR SELECT USING (true);

-- Only authenticated admins can update or delete
CREATE POLICY "reservations_admin_update" ON public.reservations
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "reservations_admin_delete" ON public.reservations
  FOR DELETE USING (auth.role() = 'authenticated');

-- ─── Sample seed data ─────────────────────────────────────────────────────────

INSERT INTO public.reservations
  (service_id, customer_name, customer_phone, reservation_date, start_time, end_time, status, note)
VALUES
  ('mali-nogomet', 'Ivan Horvat',     '+385 91 234 5678', '2026-05-11', '09:00', '10:00', 'potvrđeno', 'Trebamo 2 gola i pumpu za loptu'),
  ('stolni-tenis', 'Marija Kovač',    '+385 95 876 5432', '2026-05-11', '14:00', '15:00', 'novo',      null),
  ('treninzi',     'Ante Perić',      '+385 98 111 2233', '2026-05-11', '18:00', '19:30', 'plaćeno',   'Grupni trening, juniori U15'),
  ('rodendani',    'Petra Jurić',     '+385 91 555 6677', '2026-05-12', '11:00', '14:00', 'potvrđeno', 'Dječji rođendan, 15 djece, torta u 13h'),
  ('caffe-bar',    'Tomislav Blažić', '+385 92 333 4455', '2026-05-12', '17:00', '19:00', 'novo',      'Proslava godišnjice, oko 20 osoba'),
  ('mali-nogomet', 'Josip Matić',     '+385 99 777 8899', '2026-05-13', '10:00', '11:00', 'otkazano',  null),
  ('stolni-tenis', 'Ana Novaković',   '+385 91 222 3344', '2026-05-14', '15:00', '16:00', 'novo',      'Molim mirne stolove, ima malog'),
  ('treninzi',     'Luka Tomić',      '+385 98 444 5566', '2026-05-15', '08:00', '09:30', 'potvrđeno', 'Individualni trening'),
  ('mali-nogomet', 'Nikola Babić',    '+385 95 666 7788', '2026-05-15', '16:00', '17:00', 'plaćeno',   '2×5 igrača, teren 2'),
  ('caffe-bar',    'Katarina Šimić',  '+385 91 888 9900', '2026-05-16', '19:00', '21:00', 'novo',      'Poslovni ručak, 8 osoba'),
  ('rodendani',    'Marin Vuković',   '+385 92 111 2200', '2026-05-17', '12:00', '15:00', 'potvrđeno', 'Odrasli, 30 osoba, žele DJ')
ON CONFLICT DO NOTHING;
