/**
 * Supabase SDK generic types — wires the Database shape into createBrowserClient /
 * createServerClient so that .from('table') gets typed query builders.
 *
 * Row/Insert/Update shapes mirror supabase/schema.sql exactly.
 * For the app-layer (camelCase) types used by React components, see types/app.ts.
 * For plain DB structs without SDK wiring, see types/database.ts.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ─── Enum-like string unions ──────────────────────────────────────────────────

export type ReservationStatus = 'novo' | 'potvrđeno' | 'plaćeno' | 'otkazano';
export type SlotStatus        = 'zauzeto' | 'slobodno' | 'rezervirano' | 'ceka-potvrdu';
export type ActivityType =
  | 'ns' | 'termini' | 'igraonica' | 'ples'
  | 'pilates' | 'plesni' | 'stolni-tenis' | 'judo';
export type LocationId = 'teren' | 'dvorana-1' | 'dvorana-2';
export type UserRole   = 'admin' | 'staff';

// ─── Row types (snake_case — match schema.sql columns exactly) ────────────────

export interface ServiceRow {
  id: string;
  name: string;
  description: string | null;
  duration_minutes: number;
  price_from_eur: number;
  emoji: string | null;
  color_class: string | null;
  border_class: string | null;
  bg_class: string | null;
  active: boolean;
  created_at: string;
}

export interface LocationRow {
  id: LocationId;
  label: string;
  short_label: string;
  emoji: string | null;
  display_range_start: number;
  display_range_end: number;
  operating_weekday_start: number;
  operating_weekday_end: number;
  operating_weekend_start: number;
  operating_weekend_end: number;
}

export interface ScheduleSlotRow {
  id: string;
  location_id: LocationId;
  day_of_week: number;        // 1=Mon … 7=Sun
  start_hour: number;
  end_hour: number;
  activity_type: ActivityType;
  status: SlotStatus;
  created_at: string;
}

/** Matches the canonical reservations table in supabase/schema.sql. */
export interface ReservationRow {
  id: string;               // UUID — generated by Postgres (gen_random_uuid())
  service_id: string;
  reservation_date: string; // 'YYYY-MM-DD'
  start_time: string;       // 'HH:MM:SS'
  end_time: string;         // 'HH:MM:SS'
  customer_name: string;
  customer_phone: string;
  note: string;             // NOT NULL DEFAULT ''
  status: ReservationStatus;
  created_at: string;
}

export interface ProfileRow {
  id: string;            // UUID — references auth.users(id)
  email: string;
  full_name: string | null;
  role: UserRole;
  created_at: string;
}

// ─── Insert / Update types ────────────────────────────────────────────────────

export interface ReservationInsert {
  service_id: string;
  reservation_date: string;
  start_time: string;
  end_time: string;
  customer_name: string;
  customer_phone: string;
  note?: string;
  status?: ReservationStatus;
}

export interface ReservationUpdate {
  status?: ReservationStatus;
  note?: string;
  reservation_date?: string;
  start_time?: string;
  end_time?: string;
  customer_name?: string;
  customer_phone?: string;
}

export type ProfileInsert = Omit<ProfileRow, 'created_at'>;

// ─── Database shape (used by createBrowserClient / createServerClient) ────────
// Rules for hand-written Database types that satisfy the Supabase SDK generics:
//   1. Each table MUST include `Relationships: never[]` — required by GenericTable.
//      Using an intersection type (& { Relationships: [] }) prevents TypeScript's
//      conditional types from resolving Insert/Update correctly, producing `never`.
//   2. Insert/Update types must be plain interfaces, not Omit/Partial derivatives,
//      so they satisfy `Record<string, unknown>` without ambiguity.

export interface Database {
  public: {
    Tables: {
      services: {
        Row:           ServiceRow;
        Insert:        Omit<ServiceRow, 'created_at'>;
        Update:        Partial<Omit<ServiceRow, 'id' | 'created_at'>>;
        Relationships: never[];
      };
      locations: {
        Row:           LocationRow;
        Insert:        LocationRow;
        Update:        Partial<Omit<LocationRow, 'id'>>;
        Relationships: never[];
      };
      schedule_slots: {
        Row:           ScheduleSlotRow;
        Insert:        Omit<ScheduleSlotRow, 'created_at'>;
        Update:        Partial<Omit<ScheduleSlotRow, 'id' | 'created_at'>>;
        Relationships: never[];
      };
      reservations: {
        Row:           ReservationRow;
        Insert:        ReservationInsert;
        Update:        ReservationUpdate;
        Relationships: never[];
      };
      profiles: {
        Row:           ProfileRow;
        Insert:        ProfileInsert;
        Update:        Partial<Omit<ProfileRow, 'id' | 'created_at'>>;
        Relationships: never[];
      };
    };
    // Record<never, never> ensures keyof = never so no table name matches the View overload.
    Views:     Record<never, never>;
    Functions: Record<never, never>;
    Enums:     Record<never, never>;
  };
}
